
insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('ROHIT','RATAN','USD/CAD',1.7,100);
insert into USERS(USERNAME,PASSWORD) values ('ROHIT','Rbc@123');
insert into USERS(USERNAME,PASSWORD) values ('RATAN','RAbc@123');

insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('UTSAV','RATAN','USD/EUR',2.4,50);
insert into USERS(USERNAME,PASSWORD) values ('UTSAV','Ubc@123');

insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('RATAN','SAYLI','USD/INR',100,1);
insert into USERS(USERNAME,PASSWORD) values ('SAYLI','Sbc@123');

insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('DIVYA','SAYLI','USD/JPY',0.65,100);
insert into USERS(USERNAME,PASSWORD) values ('DIVYA','Dbc@123');

insert into ORDERS(USERNAME, ORDER_TYPE, PRICE, QTY, PAIR, TIME_STAMP, SIDE) values('RATAN','MARKET',12.5, 22, 'USD/INR', '22-6-17', 'BUY');
