
--insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('ROHIT','RATAN','USD/CAD',1.7,100);
--insert into USERS(USERNAME,PASSWORD) values ('ROHIT','Rbc@123');
--insert into USERS(USERNAME,PASSWORD) values ('RATAN','RAbc@123');
--
--insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('UTSAV','RATAN','USD/EUR',2.4,50);
--insert into USERS(USERNAME,PASSWORD) values ('UTSAV','Ubc@123');
--
--insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('RATAN','SAYLI','USD/INR',100,1);
--insert into USERS(USERNAME,PASSWORD) values ('SAYLI','Sbc@123');
--
--insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('DIVYA','SAYLI','USD/JPY',0.65,100);
--insert into USERS(USERNAME,PASSWORD) values ('DIVYA','Dbc@123');
--
--insert into ORDERS(USERNAME, ORDER_TYPE, PRICE, QTY, PAIR, TIME_STAMP, SIDE) values('RATAN','MARKET',12.5, 22, 'USD/INR', '22-6-17', 'BUY');

insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('ROHIT','RATAN','USD/CAD',1.7,100);
insert into USERS(USERNAME,PASSWORD) values ('ROHIT','Rbc@123');
insert into USERS(USERNAME,PASSWORD) values ('RATAN','RAbc@123');

insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('UTSAV','RATAN','USD/INR',2.4,50);
insert into USERS(USERNAME,PASSWORD) values ('UTSAV','Ubc@123');

insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('RATAN','SAYLI','USD/CHF',100,10);
insert into USERS(USERNAME,PASSWORD) values ('SAYLI','Sbc@123');

insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('DIVYA','SAYLI','USD/JPY',0.65,100);
insert into USERS(USERNAME,PASSWORD) values ('DIVYA','Dbc@123');

insert into SUC_TRANSACTION(BUYER,SELLER,PAIR,PRICE,QTY) values('UTSAV','SAYLI','INR/JPY',1.5,100);

--insert into ORDERS(USERNAME, ORDER_TYPE, PRICE, QTY, PAIR, TIME_STAMP, SIDE) values('RATAN','MARKET',0, 50, 'USD/INR', '22-6-17', 'BUY');
--insert into ORDERS(USERNAME, ORDER_TYPE, PRICE, QTY, PAIR, TIME_STAMP, SIDE) values('ROHIT','MARKET',0, 50, 'USD/INR', '22-6-17', 'BUY');
insert into ORDERS(USERNAME, ORDER_TYPE, PRICE, QTY, PAIR, TIME_STAMP, SIDE) values('ROHIT','LIMIT',1.6, 50, 'USD/CAD', '2017.07.13.01.14.55', 'SELL');
insert into ORDERS(USERNAME, ORDER_TYPE, PRICE, QTY, PAIR, TIME_STAMP, SIDE) values('RATAN','MARKET',0, 50, 'USD/JPY', '2017.07.13.03.14.55', 'BUY');
insert into ORDERS(USERNAME, ORDER_TYPE, PRICE, QTY, PAIR, TIME_STAMP, SIDE) values('UTSAV','LIMIT',60, 50, 'USD/IND', '2017.07.13.04.14.55', 'SELL');
insert into ORDERS(USERNAME, ORDER_TYPE, PRICE, QTY, PAIR, TIME_STAMP, SIDE) values('SAYLI','MARKET',1.6, 50, 'USD/CHF', '2017.07.13.05.14.55', 'BUY');
insert into ORDERS(USERNAME, ORDER_TYPE, PRICE, QTY, PAIR, TIME_STAMP, SIDE) values('DIVYA','MARKET',1.6, 50, 'INR/JPY', '2017.07.14.05.14.55', 'BUY');